version: "3.7"
services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  portia:
    image: scrapinghub/portia
    restart: always
    volumes:
      - ./data:/app/data/projects:rw
    ports:
      - 9001:9001      
  jupyter:
    image: jupyter/datascience-notebook:latest
    restart: always
    ports:
      - 7888:8888      
  pyspider:
    image: jupyter/datascience-notebook:latest
    restart: always
    ports:
      - 8888:8888
  phantomjs:
    image: binux/pyspider:latest
    command: phantomjs
  result:
    image: binux/pyspider:latest
    external_links:
      - sqldb0
      - rabbitmq0
    command: result_worker
  processor:
    image: binux/pyspider:latest
    external_links:
      - sqldb0
      - rabbitmq0
    command: processor
  fetcher:
    image: binux/pyspider:latest
    external_links:
      - rabbitmq0
    links:
      - phantomjs
    command : fetcher
  scheduler:
    image: binux/pyspider:latest
    external_links:
      - sqldb0
      - rabbitmq0
    command: scheduler
  webui:
    image: binux/pyspider:latest
    external_links:
      - sqldb0
      - rabbitmq0
    links:
      - scheduler
      - phantomjs
    command: webui
    ports:
      - "5000:5000"